version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user_developer
      POSTGRES_PASSWORD: user_developer
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_developer -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - shared-network

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user_developer@developer.ru
      PGADMIN_DEFAULT_PASSWORD: user_developer
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - shared-network
      
networks:
  shared-network:
    driver: bridge