// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Study.Lab3.Storage.Database;

#nullable disable

namespace Study.Lab3.Storage.PostgreSQL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250419201726_FixRelationsInSubjectGroup")]
    partial class FixRelationsInSubjectGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Group", b =>
            {
                b.Property<Guid>("IsnGroup")
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.HasKey("IsnGroup");

                b.ToTable("Groups");
            });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Student", b =>
            {
                b.Property<Guid>("IsnStudent")
                    .HasColumnType("uuid");

                b.Property<int>("Age")
                    .HasColumnType("integer");

                b.Property<Guid>("IsnGroup")
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("PatronymicName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<int>("Sex")
                    .HasColumnType("integer");

                b.Property<string>("SurName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("IsnStudent");

                b.HasIndex("IsnGroup");

                b.ToTable("Students");
            });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Subject", b =>
            {
                b.Property<Guid>("IsnSubject")
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.HasKey("IsnSubject");

                b.ToTable("Subjects");
            });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.SubjectGroup", b =>
            {
                b.Property<Guid>("IsnSubject")
                    .HasColumnType("uuid");

                b.Property<Guid>("IsnGroup")
                    .HasColumnType("uuid");

                b.HasKey("IsnSubject", "IsnGroup");

                b.HasIndex("IsnGroup");

                b.HasIndex("IsnSubject", "IsnGroup");

                b.ToTable("SubjectsGroups");
            });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Student", b =>
            {
                b.HasOne("Study.Lab3.Storage.Models.University.Group", "Group")
                    .WithMany("Students")
                    .HasForeignKey("IsnGroup")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Group");
            });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.SubjectGroup", b =>
            {
                b.HasOne("Study.Lab3.Storage.Models.University.Group", "Group")
                    .WithMany("SubjectGroups")
                    .HasForeignKey("IsnGroup")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                    .WithMany("GroupSubjects")
                    .HasForeignKey("IsnSubject")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Group");

                b.Navigation("Subject");
            });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Group", b =>
            {
                b.Navigation("Students");

                b.Navigation("SubjectGroups");
            });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Subject", b =>
            {
                b.Navigation("GroupSubjects");
            });
#pragma warning restore 612, 618
        }
    }
}
