// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Study.Lab3.Storage.Database;

#nullable disable

namespace Study.Lab3.Storage.PostgreSQL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Customer", b =>
                {
                    b.Property<Guid>("IsnCustomer")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IsnCustomer");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Genre", b =>
                {
                    b.Property<Guid>("IsnGenre")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IsnGenre");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Hall", b =>
                {
                    b.Property<Guid>("IsnHall")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RowsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("IsnHall");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Movie", b =>
                {
                    b.Property<Guid>("IsnMovie")
                        .HasColumnType("uuid");

                    b.Property<int>("AgeRating")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("IsnMovie");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.MovieGenre", b =>
                {
                    b.Property<Guid>("IsnMovie")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnGenre")
                        .HasColumnType("uuid");

                    b.HasKey("IsnMovie", "IsnGenre");

                    b.HasIndex("IsnGenre");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Seat", b =>
                {
                    b.Property<Guid>("IsnSeat")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IsnHall")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("IsnSeat");

                    b.HasIndex("IsnHall");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Session", b =>
                {
                    b.Property<Guid>("IsnSession")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IsnHall")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnMovie")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IsnSession");

                    b.HasIndex("IsnHall");

                    b.HasIndex("IsnMovie");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Ticket", b =>
                {
                    b.Property<Guid>("IsnTicket")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnCustomer")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnSeat")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnSession")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TicketCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IsnTicket");

                    b.HasIndex("IsnCustomer");

                    b.HasIndex("IsnSeat");

                    b.HasIndex("IsnSession");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.HospitalStore.Order", b =>
                {
                    b.Property<Guid>("IsnOrder")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnPatient")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnProduct")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("IsnOrder");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.HospitalStore.Patient", b =>
                {
                    b.Property<Guid>("IsnPatient")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MedicalCardId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IsnPatient");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.HospitalStore.Product", b =>
                {
                    b.Property<Guid>("IsnProduct")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("IsnProduct");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Library.AuthorBooks", b =>
                {
                    b.Property<Guid>("IsnAuthor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnBook")
                        .HasColumnType("uuid");

                    b.HasKey("IsnAuthor", "IsnBook");

                    b.HasIndex("IsnBook");

                    b.HasIndex("IsnAuthor", "IsnBook");

                    b.ToTable("AuthorBooks");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Library.Authors", b =>
                {
                    b.Property<Guid>("IsnAuthor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IsnTeacher")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PatronymicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IsnAuthor");

                    b.HasIndex("IsnTeacher")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Library.Books", b =>
                {
                    b.Property<Guid>("IsnBook")
                        .HasColumnType("uuid");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IsnBook");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.Menu", b =>
                {
                    b.Property<Guid>("IsnMenu")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IsnRestaurant")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IsnMenu");

                    b.HasIndex("IsnRestaurant");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.MenuItem", b =>
                {
                    b.Property<Guid>("IsnMenuItem")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IsnMenu")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("IsnMenuItem");

                    b.HasIndex("IsnMenu");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.OrderItem", b =>
                {
                    b.Property<Guid>("IsnOrderItem")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnMenuItem")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnOrder")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("IsnOrderItem");

                    b.HasIndex("IsnMenuItem");

                    b.HasIndex("IsnOrder");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("IsnRestaurant")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WorkingHours")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IsnRestaurant");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.RestaurantOrder", b =>
                {
                    b.Property<Guid>("IsnOrder")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("IsnRestaurant")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("integer");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.HasKey("IsnOrder");

                    b.HasIndex("IsnRestaurant");

                    b.ToTable("RestaurantOrders");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Announcement", b =>
                {
                    b.Property<Guid>("IsnAnnouncement")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IsnTeacher")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IsnAnnouncement");

                    b.HasIndex("IsnTeacher");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.AnnouncementGroup", b =>
                {
                    b.Property<Guid>("IsnAnnouncement")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnGroup")
                        .HasColumnType("uuid");

                    b.HasKey("IsnAnnouncement", "IsnGroup");

                    b.HasIndex("IsnGroup");

                    b.HasIndex("IsnAnnouncement", "IsnGroup");

                    b.ToTable("AnnouncementGroups");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Assignment", b =>
                {
                    b.Property<Guid>("IsnAssignment")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IsnAssignment");

                    b.HasIndex("IsnSubject");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Exam", b =>
                {
                    b.Property<Guid>("IsnExam")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer");

                    b.HasKey("IsnExam");

                    b.HasIndex("IsnSubject");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.ExamRegistration", b =>
                {
                    b.Property<Guid>("IsnExamRegistration")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnExam")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnStudent")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IsnExamRegistration");

                    b.HasIndex("IsnExam");

                    b.HasIndex("IsnStudent");

                    b.ToTable("ExamRegistrations");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.ExamResult", b =>
                {
                    b.Property<Guid>("IsnExamResult")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IsnExamRegistration")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("IsnExamResult");

                    b.HasIndex("IsnExamRegistration")
                        .IsUnique();

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Grade", b =>
                {
                    b.Property<Guid>("IsnGrade")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GradeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IsnStudent")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("IsnGrade");

                    b.HasIndex("IsnStudent");

                    b.HasIndex("IsnSubject");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Group", b =>
                {
                    b.Property<Guid>("IsnGroup")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IsnGroup");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Material", b =>
                {
                    b.Property<Guid>("IsnMaterial")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IsnMaterial");

                    b.HasIndex("IsnSubject");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Profcom", b =>
                {
                    b.Property<Guid>("IsnProfcom")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnStudent")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProfcomDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IsnProfcom");

                    b.HasIndex("IsnStudent");

                    b.HasIndex("IsnSubject");

                    b.ToTable("TheProfcom");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Sportclub", b =>
                {
                    b.Property<Guid>("IsnSportclub")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnStudent")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SportclubDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IsnSportclub");

                    b.HasIndex("IsnStudent");

                    b.HasIndex("IsnSubject");

                    b.ToTable("Sportclub");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Student", b =>
                {
                    b.Property<Guid>("IsnStudent")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid>("IsnGroup")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PatronymicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IsnStudent");

                    b.HasIndex("IsnGroup");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Subject", b =>
                {
                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IsnSubject");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.SubjectGroup", b =>
                {
                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnGroup")
                        .HasColumnType("uuid");

                    b.HasKey("IsnSubject", "IsnGroup");

                    b.HasIndex("IsnGroup");

                    b.HasIndex("IsnSubject", "IsnGroup");

                    b.ToTable("SubjectsGroups");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Teacher", b =>
                {
                    b.Property<Guid>("IsnTeacher")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PatronymicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IsnTeacher");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.TeacherSubject", b =>
                {
                    b.Property<Guid>("IsnTeacher")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IsnSubject")
                        .HasColumnType("uuid");

                    b.HasKey("IsnTeacher", "IsnSubject");

                    b.HasIndex("IsnSubject");

                    b.HasIndex("IsnTeacher", "IsnSubject");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.MovieGenre", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Cinema.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("IsnGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.Cinema.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("IsnMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Seat", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Cinema.Hall", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("IsnHall")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Session", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Cinema.Hall", "Hall")
                        .WithMany("Sessions")
                        .HasForeignKey("IsnHall")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.Cinema.Movie", "Movie")
                        .WithMany("Sessions")
                        .HasForeignKey("IsnMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Ticket", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Cinema.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("IsnCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.Cinema.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("IsnSeat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.Cinema.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("IsnSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Seat");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Library.AuthorBooks", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Library.Authors", "Author")
                        .WithMany("AuthorBook")
                        .HasForeignKey("IsnAuthor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.Library.Books", "Book")
                        .WithMany("AuthorBook")
                        .HasForeignKey("IsnBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Library.Authors", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Teacher", "Teacher")
                        .WithOne("Author")
                        .HasForeignKey("Study.Lab3.Storage.Models.Library.Authors", "IsnTeacher");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.Menu", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Restaurants.Restaurant", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("IsnRestaurant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.MenuItem", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Restaurants.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("IsnMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.OrderItem", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Restaurants.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("IsnMenuItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.Restaurants.RestaurantOrder", "RestaurantOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("IsnOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("RestaurantOrder");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.RestaurantOrder", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.Restaurants.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("IsnRestaurant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Announcement", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Teacher", "Teacher")
                        .WithMany("Announcements")
                        .HasForeignKey("IsnTeacher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.AnnouncementGroup", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Announcement", "Announcement")
                        .WithMany("AnnouncementGroups")
                        .HasForeignKey("IsnAnnouncement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.University.Group", "Group")
                        .WithMany("GroupAnnouncements")
                        .HasForeignKey("IsnGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Assignment", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                        .WithMany("Assignments")
                        .HasForeignKey("IsnSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Exam", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("IsnSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.ExamRegistration", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Exam", "Exam")
                        .WithMany("Registrations")
                        .HasForeignKey("IsnExam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.University.Student", "Student")
                        .WithMany("ExamRegistrations")
                        .HasForeignKey("IsnStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.ExamResult", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.ExamRegistration", "Registration")
                        .WithOne("Result")
                        .HasForeignKey("Study.Lab3.Storage.Models.University.ExamResult", "IsnExamRegistration")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Grade", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("IsnStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("IsnSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Material", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                        .WithMany("Materials")
                        .HasForeignKey("IsnSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Profcom", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Student", "Student")
                        .WithMany()
                        .HasForeignKey("IsnStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("IsnSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Sportclub", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Student", "Student")
                        .WithMany("Sportclubs")
                        .HasForeignKey("IsnStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                        .WithMany("Sportclubs")
                        .HasForeignKey("IsnSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Student", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("IsnGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.SubjectGroup", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Group", "Group")
                        .WithMany("SubjectGroups")
                        .HasForeignKey("IsnGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                        .WithMany("GroupSubjects")
                        .HasForeignKey("IsnSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.TeacherSubject", b =>
                {
                    b.HasOne("Study.Lab3.Storage.Models.University.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("IsnSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Study.Lab3.Storage.Models.University.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("IsnTeacher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Hall", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Movie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Cinema.Session", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Library.Authors", b =>
                {
                    b.Navigation("AuthorBook");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Library.Books", b =>
                {
                    b.Navigation("AuthorBook");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.Menu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.Restaurant", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.Restaurants.RestaurantOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Announcement", b =>
                {
                    b.Navigation("AnnouncementGroups");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Exam", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.ExamRegistration", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Group", b =>
                {
                    b.Navigation("GroupAnnouncements");

                    b.Navigation("Students");

                    b.Navigation("SubjectGroups");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Student", b =>
                {
                    b.Navigation("ExamRegistrations");

                    b.Navigation("Grades");

                    b.Navigation("Sportclubs");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Subject", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Exams");

                    b.Navigation("Grades");

                    b.Navigation("GroupSubjects");

                    b.Navigation("Materials");

                    b.Navigation("Sportclubs");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("Study.Lab3.Storage.Models.University.Teacher", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Author");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
