name: Build & Test

on:
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]  # Запуск при каждом обновлении PR
  push:
    branches:
      - master
      - master-base

jobs:
  build:
    runs-on: ubuntu-22.04  # Используем конкретную версию Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check available .NET versions
        run: apt list --installed | grep dotnet

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Устанавливает последнюю доступную 8.0 версию

      - name: Install .NET 8.0 SDK manually (если не установлено)
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0

      - name: Start restoring dependencies
        run: echo "🔹 Starting to restore dependencies..."

      - name: Restore dependencies
        run: dotnet restore

      - name: Dependencies restored
        run: echo "✔️ Dependencies restored successfully!"

      - name: Start building the project
        run: echo "🔹 Starting to build the project..."

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Build completed
        run: echo "✔️ Project build completed successfully!"

      - name: Start running tests
        run: echo "🔹 Starting to run tests..."

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Tests completed
        run: echo "✔️ Tests completed successfully!"
