name: .NET Code Formatting

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout репозитория с полным историей
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Загружает всю историю репозитория

      # Шаг 2: Проверка установленных версий .NET
      - name: Check available .NET versions
        run: apt list --installed | grep dotnet

      # Шаг 3: Установка последней доступной версии .NET (8.0.x)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Устанавливает последнюю доступную 8.0 версию

      # Шаг 4: Установка .NET 8.0 SDK вручную (если не установлено)
      - name: Install .NET 8.0 SDK manually (если не установлено)
        run: |
          # Загрузка и установка .NET 8.0 SDK вручную, если он не был установлен
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0

      # Шаг 5: Получаем список изменённых файлов
      - name: Get changed files
        id: changed-files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
          # Set output using environment file method
          echo "changed_files=$(cat changed_files.txt)" >> $GITHUB_ENV

      # Шаг 6: Проверка, требует ли код форматирования в изменённых файлах
      - name: Verify .NET code formatting for changed files
        run: |
          echo "Verifying .NET code formatting for changed files..."
          dotnet format ${{ env.changed_files }} --verify-no-changes
        continue-on-error: true  # В случае отсутствия изменений не завершать весь процесс

      # Шаг 7: Завершаем работу, если форматирование не требуется
      - name: Check if formatting is needed
        if: ${{ steps.changed-files.outcome == 'success' }}
        run: |
          echo "No formatting needed. Exiting the action early."
          exit 0

      # Шаг 8: Если форматирование нужно, применяем его
      - name: Apply .NET code formatting on changed files
        if: ${{ steps.changed-files.outcome != 'success' }}
        run: |
          echo "Applying .NET code formatting on changed files..."
          dotnet format ${{ env.changed_files }}
