name: .NET Code Formatting

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_run:
    workflows: ["Branch Name Check"]  # Ожидаем завершения Branch Name Check
    types:
      - completed  # Сработает, когда предыдущий workflow завершится

jobs:
  formatting:
    runs-on: ubuntu-22.04
    needs: check-branch-name  # Устанавливаем зависимость от Branch Name Check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check available .NET versions
        run: apt list --installed | grep dotnet

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET 8.0 SDK manually (если не установлено)
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0

      - name: Verify .NET code formatting (check if changes are needed)
        run: |
          echo "Verifying .NET code formatting..."
          dotnet format Study.sln --verify-no-changes

      - name: Apply .NET code formatting on solution
        run: |
          echo "Applying .NET code formatting on solution..."
          dotnet format Study.sln