name: Update Changelog

on:
  pull_request:
    types: [closed]  # Запускаем workflow, когда PR закрыт (merged)

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Загружаем полную историю коммитов

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Extract PR commits and filter
        id: pr_commits
        run: |
          DATE=$(date +'%Y-%m-%d')
          AUTHOR="${{ github.actor }}"
          
          # Получаем список всех коммитов в PR
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          COMMITS=$(git log --pretty=format:"%h %s (Автор: %an)" $BASE_SHA..HEAD)
          
          # Фильтруем коммиты с [Private]
          FILTERED_COMMITS=$(echo "$COMMITS" | grep -v '\[Private\]')

          # Если после фильтрации список пуст - пропускаем обновление CHANGELOG
          if [ -z "$FILTERED_COMMITS" ]; then
            echo "All commits contain [Private], skip updating CHANGELOG."
            exit 0
          fi

          # Формируем строку для CHANGELOG
          echo "" >> CHANGELOG.md
          echo "$DATE - PR #${{ github.event.pull_request.number }} от @${AUTHOR}" >> CHANGELOG.md
          echo "$FILTERED_COMMITS" >> CHANGELOG.md

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG with latest PR commits"
          git push
