name: Update Changelog

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Загружаем полную историю коммитов

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Switch to master branch
        run: |
          git checkout master  # Если у вас main, замените на main
          git pull origin master  # Обновляем локальную копию

      - name: Ensure CHANGELOG.md exists
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "CHANGELOG.md not found. Creating a new one."
            touch CHANGELOG.md
            git add CHANGELOG.md
            git commit -m "Initialize CHANGELOG.md" || echo "No initial commit needed"
            git push origin master || echo "No changes to push"
          fi

      - name: Extract PR commits and filter
        id: pr_commits
        run: |
          set -e  # Прерывание скрипта при критических ошибках
          
          DATE=$(date +'%Y-%m-%d')
          AUTHOR="${{ github.actor }}"
          
          # Получаем SHA базовой ветки
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          echo "Base SHA: $BASE_SHA"
          echo "Current HEAD: $(git rev-parse HEAD)"

          # Получаем список всех коммитов в PR
          COMMITS=$(git log --pretty=format:"%h %s (Автор: %an)" $BASE_SHA..HEAD || true)
          
          echo "Commits found in range:"
          echo "$COMMITS"

          # Фильтруем коммиты с [Private]
          FILTERED_COMMITS=$(echo "$COMMITS" | grep -v '\[Private\]' || true)

          echo "Filtered commits:"
          echo "$FILTERED_COMMITS"

          # Если после фильтрации список пуст - просто завершаем работу без ошибки
          if [ -z "$FILTERED_COMMITS" ]; then
            echo "All commits contain [Private], skipping CHANGELOG update."
            exit 0
          fi

          # Добавляем изменения в CHANGELOG.md
          {
            echo ""
            echo "$DATE - PR #${{ github.event.pull_request.number }} от @${AUTHOR}"
            echo "$FILTERED_COMMITS"
          } >> CHANGELOG.md

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG with latest PR commits" || echo "No changes to commit"
          git push origin master || echo "No changes to push"
