name: Update Changelog on PR update

on:
  pull_request:
    types: [opened, synchronize, edited]  # Срабатывает при открытии, синхронизации и изменении PR
    branches:
      - master  # Только для PR в ветку master

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Загружаем полную историю коммитов

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Ensure CHANGELOG.md exists
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "CHANGELOG.md not found. Creating a new one."
            touch CHANGELOG.md
            git add CHANGELOG.md
            git commit -m "Initialize CHANGELOG.md"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:refs/heads/${{ github.head_ref }}
          else
            echo "CHANGELOG.md already exists, checking for updates."
          fi

      - name: Extract PR details
        id: pr_details
        run: |
          DATE=$(date +'%Y-%m-%d')
          AUTHOR="${{ github.actor }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"

          echo "PR #${PR_NUMBER} - Title: ${PR_TITLE}"

          # Создаем строку записи для добавления в CHANGELOG.md
          NEW_ENTRY="### $DATE - PR #${PR_NUMBER} от @${AUTHOR}: ${PR_TITLE}"

          # Проверяем, если запись с данным PR номером уже существует, обновляем ее
          if grep -q "PR #${PR_NUMBER}" CHANGELOG.md; then
            echo "Updating existing entry for PR #${PR_NUMBER}."
            # Удаляем старую запись и добавляем новую
            sed -i "/PR #${PR_NUMBER}/,/^$/d" CHANGELOG.md
            echo -e "$NEW_ENTRY" >> CHANGELOG.md
          else
            echo "Adding new entry for PR #${PR_NUMBER}."
            echo -e "$NEW_ENTRY" >> CHANGELOG.md

      - name: Commit and push changes to PR branch
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG with latest PR title" || (echo "No changes to commit" && exit 0)
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:refs/heads/${{ github.head_ref }}

      - name: Merge PR into master
        run: |
          git checkout master
          git pull origin master
          git merge ${GITHUB_HEAD_REF} -m "Merge PR #${{ github.event.pull_request.number }} with changelog updates"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master
          git commit -m "Update CHANGELOG with latest PR commits" || (echo "No changes to commit" && exit 1)
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master || (echo "No changes to push" && exit 1)
